# Generated by Django 5.2.15 on 2026-06-30 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_grade', models.CharField(blank=True, max_length=50)),
                ('scheduled_tour_date', models.DateTimeField()),
                ('current_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('toured', 'Toured'), ('enrolled', 'Enrolled'), ('churned', 'Churned'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tours', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='leads.family')),
                ('lead_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='leads.leadsource')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='sites.location')),
            ],
            options={
                'ordering': ['-scheduled_tour_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('toured', 'Toured'), ('enrolled', 'Enrolled'), ('churned', 'Churned'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], max_length=20)),
                ('event_timestamp', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tours.tour')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_events_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_timestamp', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['current_status'], name='tours_tour_current_9c2e25_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['scheduled_tour_date'], name='tours_tour_schedul_97235b_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['location', 'current_status'], name='tours_tour_locatio_eeab3a_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['lead_source'], name='tours_tour_lead_so_6576d3_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['assigned_staff'], name='tours_tour_assigne_d12451_idx'),
        ),
        migrations.AddIndex(
            model_name='tourevent',
            index=models.Index(fields=['tour', 'event_timestamp'], name='tours_toure_tour_id_eb4b36_idx'),
        ),
        migrations.AddIndex(
            model_name='tourevent',
            index=models.Index(fields=['status'], name='tours_toure_status_707349_idx'),
        ),
        migrations.AddIndex(
            model_name='tourevent',
            index=models.Index(fields=['updated_by'], name='tours_toure_updated_a5ccca_idx'),
        ),
    ]
