# Generated by Django 5.2.15 on 2026-07-02 04:29

import django.db.models.functions.text
from django.db import migrations, models


def normalize_existing_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    normalized_emails = {}

    for user in User.objects.all().only("id", "email"):
        normalized_email = user.email.strip().lower()
        existing_user_id = normalized_emails.get(normalized_email)
        if existing_user_id is not None:
            raise RuntimeError(
                "Cannot enforce case-insensitive email uniqueness: "
                f"users {existing_user_id} and {user.id} share {normalized_email}."
            )
        normalized_emails[normalized_email] = user.id
        if user.email != normalized_email:
            User.objects.filter(id=user.id).update(email=normalized_email)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(normalize_existing_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="accounts_user_email_ci_unique",
            ),
        ),
    ]
