# Generated by Django 5.2.15 on 2026-07-02 05:01

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_accounts_user_email_ci_unique"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", apps.accounts.models.UserManager()),],
        ),
    ]
