# Generated by Django 5.2.15 on 2026-06-30 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_month', models.DateField()),
                ('cost_type', models.CharField(max_length=100)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_basis_entries', to='sites.location')),
            ],
            options={
                'verbose_name_plural': 'cost basis entries',
                'ordering': ['-reporting_month', 'location', 'cost_type'],
                'indexes': [models.Index(fields=['location', 'reporting_month'], name='reports_cos_locatio_d611ca_idx'), models.Index(fields=['cost_type'], name='reports_cos_cost_ty_52b6dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'reporting_month', 'cost_type'), name='unique_cost_basis_location_month_type'), models.CheckConstraint(condition=models.Q(('cost_amount__gte', 0)), name='cost_basis_amount_non_negative')],
            },
        ),
    ]
