# Generated by Django 5.2.15 on 2026-07-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costbasis',
            name='external_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
